# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-28 09:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PostList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pl_name', models.CharField(max_length=100)),
                ('pl_user', models.CharField(max_length=20)),
                ('pl_user_icon', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PostModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_title', models.CharField(max_length=100)),
                ('p_owner', models.CharField(max_length=20)),
                ('p_comment', models.TextField()),
                ('is_del', models.BooleanField(max_length=False)),
            ],
        ),
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_name', models.CharField(max_length=20, unique=True)),
                ('u_icon', models.ImageField(upload_to='icons')),
                ('u_password', models.CharField(max_length=256)),
                ('u_email', models.CharField(max_length=32)),
                ('u_authority', models.IntegerField(default=0)),
                ('is_del', models.BooleanField(default=False)),
                ('is_act', models.BooleanField(max_length=False)),
                ('u_posts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.PostModel')),
            ],
        ),
    ]
