# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-30 03:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PostList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='PostModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_title', models.CharField(max_length=100)),
                ('p_comment', models.TextField()),
                ('is_del', models.BooleanField(max_length=False)),
                ('p_created', models.DateTimeField(auto_now_add=True)),
                ('p_update', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_name', models.CharField(max_length=20, unique=True)),
                ('u_icon', models.ImageField(upload_to='icons')),
                ('u_password', models.CharField(max_length=256)),
                ('u_email', models.CharField(max_length=32)),
                ('u_authority', models.IntegerField(default=1)),
                ('is_del', models.BooleanField(default=False)),
                ('is_act', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='postmodel',
            name='p_user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='App.UserModel'),
        ),
        migrations.AddField(
            model_name='postlist',
            name='pl_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.PostModel'),
        ),
        migrations.AddField(
            model_name='postlist',
            name='pl_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.UserModel'),
        ),
    ]
