# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-30 08:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='is_del',
            field=models.BooleanField(default=False),
        ),
    ]
